jobs:
  api:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/repo
    steps:
      - run:
          name: Audit
          command: echo 'hi api'
  mgt:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/repo
    steps:
      - run:
          name: Audit
          command: echo 'hi mgt'
  build:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Detect and laucnh
          command: |
            source .circleci/commitRange.sh
            source .circleci/changeDetect.sh

            echo $deployServicesNames

            # set -x
            # for service-name in $deployServicesNames; do
            #   echo $service-name
            #   curl -s -u $CIRCLE_TOKEN: \
            #     -d build_parameters[CIRCLE_JOB]=$service-name \
            #     https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
            # done
      
version: 2
workflows:
  build:
    jobs:
      - build