version: 2

jobs:
  build:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Regenerate commit range
          command: .circleci/commitRange.sh
      - run:
          name: Detect changes
          command: |
            source .circleci/detectChanges.sh
            echo 'export DEPLOY_SERVICES_NAMES=$deployServicesNames' >> $BASH_ENV
      - run:
          name: Launch jobs
          command: .circleci/launchJobs.sh
  api:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/repo
    steps:
      - run:
          name: Audit
          command: echo 'hi api'
  mgt:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/repo
    steps:
      - run:
          name: Audit
          command: echo 'hi mgt'            
      
workflows:
  version: 2
  build:
    jobs:
      - build