version: 2

jobs:
  build:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Regenerate commit range
          command: .circleci/commitRange.sh
      - run:
          name: Detect changes
          command: .circleci/detectChanges.sh
      - run:
          name: Launch jobs
          command: .circleci/launchJobs.sh
  api:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Audit
          command: ls -la
  mgt:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Audit
          command: ls -la       
      
workflows:
  version: 2
  build:
    jobs:
      - build