version: 2

jobs:
  build:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Regenerate commit range
          command: .circleci/commitRange.sh
      - run:
          name: Detect and launch
          command: |
            source .circleci/changeDetect.sh

            echo $deployServicesNames

            set -x
            for serviceName in $deployServicesNames; do
              echo $serviceName
              curl -s -u $CIRCLE_TOKEN: \
                -d build_parameters[CIRCLE_JOB]=$serviceName \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
            done
  api:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/repo
    steps:
      - run:
          name: Audit
          command: echo 'hi api'
  mgt:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/repo
    steps:
      - run:
          name: Audit
          command: echo 'hi mgt'            
      
workflows:
  version: 2
  build:
    jobs:
      - build