version: 2

jobs:
  test:
    docker:
      - image: edus44/alpine-git-curl-bash-jq
    working_directory: ~/repo
    steps:
      - run: 
          name: hi
          command: |
            echo -e "api\nworker\nmgt" | circleci tests split
      
workflows:
  version: 2
  launcher:
    jobs:
      - test