
parameters:
  service-name:
    type: string
    default: "caca"
    
orbs:
  labs: gigigo/labs@dev:latest
  compare-url: iynere/compare-url@1.1.0

jobs:

  build:
    docker:
      - image: circleci/circleci-cli
    environment:
      IMAGETAG: << pipeline.parameters.service-name >>
    working_directory: ~/repo
    steps:
      - run:
          name: Audit
          command: echo 'hi << pipeline.parameters.service-name >>'
      
version: 2.1
workflows:
  build:
    jobs:
      - build